services:
  - type: web
    name: prediccion-popularidad-canciones
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /salud
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
